#version 310 es
layout(local_size_x = 64) in;

struct Particle { vec3 position; vec3 v; mat3 C; };
struct Cell { int vx; int vy; int vz; int mass; };

layout(std430, binding = 0) readonly buffer Particles { Particle particles[]; };
layout(std430, binding = 1) buffer Cells { Cell cells[]; };
layout(std430, binding = 2) buffer Densities { float densities[]; };

uniform int   uNumParticles;
uniform vec3  uBoxSize;
uniform float uDt;
uniform float uFixedM;
uniform float uFixedMInv;
uniform float uStiffness;        // 50.0
uniform float uRestDensity;      // 3.0
uniform float uViscosity;        // 0.1

int   encodeF(float x) { return int(x * uFixedM); }
float decodeF(int   x) { return float(x) * uFixedMInv; }

int cellIndex(vec3 c) {
    return int(c.x) * int(uBoxSize.y) * int(uBoxSize.z)
         + int(c.y) * int(uBoxSize.z) + int(c.z);
}

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= uint(uNumParticles)) return;

    Particle p = particles[id];
    vec3 cellIndexF = floor(p.position);
    vec3 cellDiff   = p.position - (cellIndexF + 0.5);

    vec3 w[3];
    w[0] = 0.5 * (0.5 - cellDiff) * (0.5 - cellDiff);
    w[1] = 0.75 - cellDiff * cellDiff;
    w[2] = 0.5 * (0.5 + cellDiff) * (0.5 + cellDiff);


    float density = 0.0;
    for (int gx = 0; gx < 3; gx++)
    for (int gy = 0; gy < 3; gy++)
    for (int gz = 0; gz < 3; gz++) {
        float weight = w[gx].x * w[gy].y * w[gz].z;
        vec3 cellX = cellIndexF + vec3(float(gx), float(gy), float(gz)) - 1.0;
        density += decodeF(cells[cellIndex(cellX)].mass) * weight;
    }
    densities[id] = density;


    float volume   = 1.0 / max(density, 1e-6);
    float pressure = max(0.0, uStiffness * (density / uRestDensity - 1.0));

    mat3 stress = mat3(
        -pressure, 0, 0,
        0, -pressure, 0,
        0, 0, -pressure);

    mat3 dudv  = p.C;
    mat3 strain = dudv + transpose(dudv);
    stress += uViscosity * strain;

    mat3 eq16 = -volume * 4.0 * stress * uDt;


    for (int gx = 0; gx < 3; gx++)
    for (int gy = 0; gy < 3; gy++)
    for (int gz = 0; gz < 3; gz++) {
        float weight = w[gx].x * w[gy].y * w[gz].z;
        vec3 cellX = cellIndexF + vec3(float(gx), float(gy), float(gz)) - 1.0;
        vec3 cellDist = (cellX + 0.5) - p.position;
        vec3 momentum = eq16 * weight * cellDist;
        int ci = cellIndex(cellX);
        atomicAdd(cells[ci].vx, encodeF(momentum.x));
        atomicAdd(cells[ci].vy, encodeF(momentum.y));
        atomicAdd(cells[ci].vz, encodeF(momentum.z));
    }
}