#version 310 es
layout(local_size_x = 64) in;

struct Particle { vec3 position; vec3 v; mat3 C; };
layout(std430, binding = 0) readonly buffer Particles { Particle particles[]; };
layout(std430, binding = 1) readonly buffer Densities { float densities[]; };
layout(std430, binding = 2) buffer DensityGrid { int densityGrid[]; };

uniform int   uNumParticles;
uniform vec3  uDensityGridSize;
uniform float uDensityM;

int encodeF(float x) { return int(x * uDensityM); }

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= uint(uNumParticles)) return;

    Particle p = particles[id];
    vec3 cellIndexF = floor(p.position);
    vec3 cellDiff   = p.position - (cellIndexF + 0.5);

    vec3 w[3];
    w[0] = 0.5 * (0.5 - cellDiff) * (0.5 - cellDiff);
    w[1] = 0.75 - cellDiff * cellDiff;
    w[2] = 0.5 * (0.5 + cellDiff) * (0.5 + cellDiff);

    for (int gx = 0; gx < 3; gx++)
    for (int gy = 0; gy < 3; gy++)
    for (int gz = 0; gz < 3; gz++) {
        float weight = w[gx].x * w[gy].y * w[gz].z;
        vec3 cellX = cellIndexF + vec3(float(gx), float(gy), float(gz)) - 1.0;
        int ci = int(cellX.x) * int(uDensityGridSize.y) * int(uDensityGridSize.z)
               + int(cellX.y) * int(uDensityGridSize.z)
               + int(cellX.z);
        atomicAdd(densityGrid[ci], encodeF(densities[id] * weight));
    }
}