#version 310 es
layout(local_size_x = 64) in;

struct Cell { int vx; int vy; int vz; int mass; };
layout(std430, binding = 0) buffer Cells { Cell cells[]; };

uniform int   uGridCount;
uniform vec3  uBoxSize;
uniform vec3  uRealBoxSize;
uniform vec3  uGravity;
uniform float uDt;
uniform float uFixedM;
uniform float uFixedMInv;
uniform vec3  uPointerCell;
uniform vec3  uPointerForce;
uniform float uPointerRadius;

int   encodeF(float x) { return int(x * uFixedM); }
float decodeF(int   x) { return float(x) * uFixedMInv; }

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= uint(uGridCount)) return;

    if (cells[id].mass == 0) return;

    float invMass = 1.0 / decodeF(cells[id].mass);
    vec3 vel = vec3(
        decodeF(cells[id].vx),
        decodeF(cells[id].vy),
        decodeF(cells[id].vz)) * invMass;


    if (uPointerCell.x >= 0.0) {
        float x = float(int(id) / int(uBoxSize.z) / int(uBoxSize.y));
        float y = float((int(id) / int(uBoxSize.z)) % int(uBoxSize.y));
        float z = float(int(id) % int(uBoxSize.z));
        float d2 = dot(uPointerCell - vec3(x, y, z), uPointerCell - vec3(x, y, z));
        float r2 = uPointerRadius * uPointerRadius;
        float strength = (1.0 - smoothstep(0.0, r2, d2)) * 0.2;
        vel += strength * uPointerForce;
    }


    vel += uGravity * uDt;

    cells[id].vx = encodeF(vel.x);
    cells[id].vy = encodeF(vel.y);
    cells[id].vz = encodeF(vel.z);


    int x = int(id) / int(uBoxSize.z) / int(uBoxSize.y);
    int y = (int(id) / int(uBoxSize.z)) % int(uBoxSize.y);
    int z = int(id) % int(uBoxSize.z);
    if (x < 2 || x > int(ceil(uRealBoxSize.x) - 3.0)) cells[id].vx = 0;
    if (y < 2 || y > int(ceil(uRealBoxSize.y) - 3.0)) cells[id].vy = 0;
    if (z < 2 || z > int(ceil(uRealBoxSize.z) - 3.0)) cells[id].vz = 0;
}